### ISSUE TITLE
The Slider is wiered on the first load of the page

### ISSUE THREAD

**Issue by ranjithmnair** [leftstick/angular-slider-easy#6]
the sliders selection area (blu color) goes out of the page on the first load of the page. when i inspect the element or open an firebug window it'becomes normal. how to overcome this

**Comment by ranjithmnair** [comment]
![image](https://cloud.githubusercontent.com/assets/16933998/12638942/e17c5c7c-c5c6-11e5-86c4-09187a7ab27d.png)

**Comment by leftstick** [comment]
Have you tried in latest chrome?

**Comment by ranjithmnair** [comment]
yes ! same problem

**Comment by leftstick** [comment]
Can you provide a plunker？

**Comment by ranjithmnair** [comment]
http://plnkr.co/edit/nFheF359ZURUpAfEOYDL?p=preview
here it seems ok .

**Comment by leftstick** [comment]
Plunker works well, right? It might be caused by your usage, can you describe more about the detail that how you used it?

**Comment by ranjithmnair** [comment]
the same way as i did in the plunkr but i change some css like height of the slider tracker and height and width of the slider handle. also this changes are made to min.css file. if i give large number the slider becomes more streched(100000).

**Comment by leftstick** [comment]
I cannot reproduce it.

But since `npm` is more popular, i modified something to make it installable via both `npm` and `bower`.

And add a short delay while render the UI, this maybe helpful in your case. Can you have a try and let me know the result?
