### ISSUE TITLE
Clicking on the slider bar does not move the handle

### ISSUE THREAD

**Issue by dyutibarma** [leftstick/angular-slider-easy#8]
While sliding or dragging the handle changes values, clicking at the desired location on the slider bar doesn't change the values or the position of the handle. Desired behavior demo-ed here - http://smartphones.specout.com/. Clicking anywhere on the slider bar will move the handle.

Is there a way to configure this?

PS: Thanks for the slider.

**Comment by leftstick** [comment]
Nice feature, it was supported in `1.1.0`, please have a try with it
